<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('permissions')->truncate();

        $permissions = [
            [
                'id' => 1,
                'name' => 'can-create-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 2,
                'name' => 'can-edit-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'name' => 'can-delete-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 4,
                'name' => 'can-view-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 5,
                'name' => 'can-view-details-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 6,
                'name' => 'can-create-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 7,
                'name' => 'can-edit-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 8,
                'name' => 'can-delete-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 9,
                'name' => 'can-view-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 10,
                'name' => 'can-view-details-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 11,
                'name' => 'can-create-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 12,
                'name' => 'can-edit-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 13,
                'name' => 'can-delete-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 14,
                'name' => 'can-create-branch',
                'guard_name' => 'web',
                'group_name' => 'Branch Management',
                'is_active' => true,
            ],
            [
                'id' => 15,
                'name' => 'can-edit-branch',
                'guard_name' => 'web',
                'group_name' => 'Branch Management',
                'is_active' => true,
            ],
            [
                'id' => 16,
                'name' => 'can-delete-branch',
                'guard_name' => 'web',
                'group_name' => 'Branch Management',
                'is_active' => true,
            ],
            [
                'id' => 17,
                'name' => 'can-view-branch',
                'guard_name' => 'web',
                'group_name' => 'Branch Management',
                'is_active' => true,
            ],
            [
                'id' => 18,
                'name' => 'can-view-details-branch',
                'guard_name' => 'web',
                'group_name' => 'Branch Management',
                'is_active' => true,
            ],
            [
                'id' => 19,
                'name' => 'can-create-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 20,
                'name' => 'can-edit-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 21,
                'name' => 'can-delete-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 22,
                'name' => 'can-view-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 23,
                'name' => 'can-view-details-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 24,
                'name' => 'can-create-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 25,
                'name' => 'can-edit-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 26,
                'name' => 'can-delete-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 27,
                'name' => 'can-view-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 28,
                'name' => 'can-view-details-employee',
                'guard_name' => 'web',
                'group_name' => 'Employee Management',
                'is_active' => true,
            ],
            [
                'id' => 29,
                'name' => 'can-create-attendance-log',
                'guard_name' => 'web',
                'group_name' => 'Attendance Log Management',
                'is_active' => true,
            ],
            [
                'id' => 30,
                'name' => 'can-edit-attendance-log',
                'guard_name' => 'web',
                'group_name' => 'Attendance Log Management',
                'is_active' => true,
            ],
            [
                'id' => 31,
                'name' => 'can-delete-attendance-log',
                'guard_name' => 'web',
                'group_name' => 'Attendance Log Management',
                'is_active' => true,
            ],
            [
                'id' => 32,
                'name' => 'can-view-attendance-log',
                'guard_name' => 'web',
                'group_name' => 'Attendance Log Management',
                'is_active' => true,
            ],
            [
                'id' => 33,
                'name' => 'can-view-details-attendance',
                'guard_name' => 'web',
                'group_name' => 'Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 34,
                'name' => 'can-create-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 35,
                'name' => 'can-edit-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 36,
                'name' => 'can-delete-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 37,
                'name' => 'can-view-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 38,
                'name' => 'can-view-details-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 39,
                'name' => 'can-view-configuration',
                'guard_name' => 'web',
                'group_name' => 'Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 40,
                'name' => 'can-edit-configuration',
                'guard_name' => 'web',
                'group_name' => 'Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 41,
                'name' => 'can-create-employee-attendance-log',
                'guard_name' => 'web',
                'group_name' => 'Employee Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 42,
                'name' => 'can-view-employee-attendance-log',
                'guard_name' => 'web',
                'group_name' => 'Employee Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 43,
                'name' => 'can-view-employee-attendance',
                'guard_name' => 'web',
                'group_name' => 'Employee Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 44,
                'name' => 'can-create-employee-attendance-request',
                'guard_name' => 'web',
                'group_name' => 'Employee Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 45,
                'name' => 'can-view-employee-attendance-request',
                'guard_name' => 'web',
                'group_name' => 'Employee Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 46,
                'name' => 'can-view-attendance-request',
                'guard_name' => 'web',
                'group_name' => 'Employee Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 47,
                'name' => 'can-approve-attendance-request',
                'guard_name' => 'web',
                'group_name' => 'Employee Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 48,
                'name' => 'can-decline-attendance-request',
                'guard_name' => 'web',
                'group_name' => 'Employee Attendance Management',
                'is_active' => true,
            ],
            [
                'id' => 49,
                'name' => 'can-create-leave-type',
                'guard_name' => 'web',
                'group_name' => 'Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 50,
                'name' => 'can-edit-leave-type',
                'guard_name' => 'web',
                'group_name' => 'Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 51,
                'name' => 'can-delete-leave-type',
                'guard_name' => 'web',
                'group_name' => 'Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 52,
                'name' => 'can-view-leave-type',
                'guard_name' => 'web',
                'group_name' => 'Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 53,
                'name' => 'can-view-details-leave-type',
                'guard_name' => 'web',
                'group_name' => 'Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 54,
                'name' => 'can-view-subscription',
                'guard_name' => 'web',
                'group_name' => 'Subscription Management',
                'is_active' => true,
            ],
            [
                'id' => 55,
                'name' => 'can-edit-subscription',
                'guard_name' => 'web',
                'group_name' => 'Subscription Management',
                'is_active' => true,
            ],
            [
                'id' => 56,
                'name' => 'can-create-leave-allocation',
                'guard_name' => 'web',
                'group_name' => 'Leave Allocation Management',
                'is_active' => true,
            ],
            [
                'id' => 57,
                'name' => 'can-edit-leave-allocation',
                'guard_name' => 'web',
                'group_name' => 'Leave Allocation Management',
                'is_active' => true,
            ],
            [
                'id' => 58,
                'name' => 'can-view-leave-allocation',
                'guard_name' => 'web',
                'group_name' => 'Leave Allocation Management',
                'is_active' => true,
            ],
            [
                'id' => 59,
                'name' => 'can-view-details-leave-allocation',
                'guard_name' => 'web',
                'group_name' => 'Leave Allocation Management',
                'is_active' => true,
            ],
            [
                'id' => 60,
                'name' => 'can-approve-leave-allocation',
                'guard_name' => 'web',
                'group_name' => 'Leave Allocation Management',
                'is_active' => true,
            ],
            [
                'id' => 61,
                'name' => 'can-view-calendar-leave',
                'guard_name' => 'web',
                'group_name' => 'Calendar Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 62,
                'name' => 'can-create-public-holiday',
                'guard_name' => 'web',
                'group_name' => 'Public Holiday Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 63,
                'name' => 'can-view-public-holiday',
                'guard_name' => 'web',
                'group_name' => 'Public Holiday Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 64,
                'name' => 'can-edit-public-holiday',
                'guard_name' => 'web',
                'group_name' => 'Public Holiday Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 65,
                'name' => 'can-delete-public-holiday',
                'guard_name' => 'web',
                'group_name' => 'Public Holiday Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 66,
                'name' => 'can-create-leave',
                'guard_name' => 'web',
                'group_name' => 'Employee Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 67,
                'name' => 'can-view-employee-leave',
                'guard_name' => 'web',
                'group_name' => 'Employee Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 68,
                'name' => 'can-approve-leave',
                'guard_name' => 'web',
                'group_name' => 'Employee Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 69,
                'name' => 'can-view-leave',
                'guard_name' => 'web',
                'group_name' => 'Employee Leave Management',
                'is_active' => true,
            ],
            [
                'id' => 70,
                'name' => 'can-view-employee-chart',
                'guard_name' => 'web',
                'group_name' => 'Employee Chart Management',
                'is_active' => true,
            ]
        ];
            
        Permission::insert($permissions);

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
